<a href="https://colab.research.google.com/github/ProfLunaLuis/Metodos_Numericos/blob/main/Gauss-Seidel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import numpy.linalg as al
from sympy import *
from scipy import linalg

A = np.array([[3, 0.1, -0.2],
              [0.1, 7, -0.3],
              [0.3, -0.2, 10]])
b = np.array([7.85, -19.3, 71.4])
print(linalg.solve(A, b))

#Declaramos C.I.
xa0=np.array([0,0,0])
xa_1=xa0[0]
xa_2=xa0[1]
xa_3=xa0[2]
# Genero matriz donde se guardan datos
A = np.zeros((10,3))
tol=0.0001
norma_inf=1
i=1
while tol<norma_inf:
#Calculo X1
 xn_1=(7.85+0.1*xa_2+0.2*xa_3)/3
#Guardar el valor de X1n
 xn_2=(-19.3-0.1*xn_1+0.3*xa_3)/7
#
 xn_3=(71.4-0.3*xa_1+0.2*xn_2)/10
# Guardo los datos de x1, x2, x3 y x4 en el vector xa
#************************************
 xa=np.array([xn_1,xn_2,xn_3])
#***********************************
 A[i]=xa
 # Calculo de las normas
 norma_inf=al.norm(A[i]-A[i-1],np.inf)/al.norm(A[i],np.inf)
 i=i+1
 xa_1=xa[0]
 xa_2=xa[1]
 xa_3=xa[2]

print(A)



[ 3.16641683 -2.50259357  6.99495562]
[[ 0.          0.          0.        ]
 [ 2.61666667 -2.79452381  7.08410952]
 [ 2.99578984 -2.49633516  7.0115733 ]
 [ 3.00089371 -2.49951677  7.00013597]
 [ 3.00002517 -2.49999453  6.9999733 ]
 [ 2.9999984  -2.50000112  6.99999922]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
