<a href="https://colab.research.google.com/github/ProfLunaLuis/Metodos_Numericos/blob/main/Jacobi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy as np
from sympy import *
#Declaramos C.I.
xa=np.array([0,0,0,0])
xa_1=xa[0]
xa_2=xa[1]
xa_3=xa[2]
xa_4=xa[3]
# Genero matriz donde se guardan datos
A = np.zeros((11, 4))
#
for i in range(1, 11, 1):
 xn_1=1/10*xa_2-1/5*xa_3+3/5
 xn_2=1/11*xa_1+1/11*xa_3-3/11*xa_4+25/11
 xn_3=-1/5*xa_1+1/10*xa_2+1/10*xa_4-11/10
 xn_4=-3/8*xa_2+1/8*xa_3+15/8
# Guardo los datos de x1, x2, x3 y x4 en el vector xa
 xa=np.array([xn_1,xn_2,xn_3,xn_4])
# En la fila i se guardan los datos de x1, x2, x3 y x4
 A[i]=xa
#Accedo a los datos del vector para que se usen en el siguiente ciclo
 xa_1=xa[0]
 xa_2=xa[1]
 xa_3=xa[2]
 xa_4=xa[3]
#
print(A)



[[ 0.          0.          0.          0.        ]
 [ 0.6         2.27272727 -1.1         1.875     ]
 [ 1.04727273  1.71590909 -0.80522727  0.88522727]
 [ 0.93263636  2.05330579 -1.04934091  1.13088068]
 [ 1.01519876  1.95369576 -0.96810863  0.97384272]
 [ 0.9889913   2.01141473 -1.0102859   1.02135051]
 [ 1.00319865  1.99224126 -0.99452174  0.99443374]
 [ 0.99812847  2.00230688 -1.00197223  1.00359431]
 [ 1.00062513  1.9986703  -0.99903558  0.99888839]
 [ 0.99967415  2.00044767 -1.00036916  1.00061919]
 [ 1.0001186   1.99976795 -0.99982814  0.99978598]]
